[package]
name = "syncify"
version = "0.1.0"
authors = ["Alexandre Leconte (Deleranax)", "Maxime Savary (GamerMine)"]
edition = "2024"
description = "A simple peer-to-peer, cross-platform file synchronization client"
readme = "../README.md"
repository = "https://github.com/Dwight-Studio/syncify"
license = "GPL-3"
keywords = ["p2p", "peer-to-peer", "cross-platform", "file", "sync"]
categories = ["filesystem", "gui", "command-line-interface"]
publish = false

[dependencies]
libsyncify = { path= "../libsyncify" }
tokio = "1.44.0"
relm4 = { version = "0.9.1", features = ["libadwaita", "gnome_47"] }
relm4-icons = { version = "0.10.0-beta.2"}
uuid = { version = "1.15.1", features = ["v4"] }
log = "0.4.26"
tr = "0.1.10"
chrono = "0.4.40"

[build-dependencies]
grass = "0.13.4"
gvdb = { version = "0.8.0", features = ["gresource"] }
